# 在知识库仓库 (.github/workflows/trigger-blog.yml) 中创建

name: Trigger Blog Build

on:
  push:
    branches: [master]
    paths:
      - '**.md'
      - '**.mdx'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.BLOG_GITHUB_TOKEN }}" \
            https://api.github.com/repos/SCUJJ-OSIG/my-blog/dispatches \
            -d '{"event_type":"build"}'
